version: "3.8"

services:
  # Nginx Web Server
  webserver:
    image: nginx:alpine
    container_name: telegram-bot-webserver
    working_dir: /var/www/telegram-bot
    volumes:
      - .:/var/www/telegram-bot
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  # PHP-FPM
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: telegram-bot-php-fpm
    working_dir: /var/www/telegram-bot
    volumes:
      - .:/var/www/telegram-bot
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    depends_on:
      - mysql
      - redis

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: telegram-bot-mysql
    command: mysqld --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: telegram-bot
      MYSQL_DATABASE: telegram-bot
      MYSQL_USER: telegram-bot
      MYSQL_PASSWORD: telegram-bot
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Redis
  redis:
    image: redis:alpine
    container_name: telegram-bot-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
